In [79]:
import numpy

numpy.__version__

'1.26.4'

In [80]:
import numpy as np  # alias

### Python Lists vs. Python Arrays vs. Numpy Arrays

In [81]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [82]:

type(L[0])

int

In [83]:

L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [84]:
type(L2[0])

str

In [85]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [86]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
# Integer array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [88]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [89]:
np.array([1, 2, 3, 4], dtype=np.float32)  # specify type

array([1., 2., 3., 4.], dtype=float32)

In [90]:
# Nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [91]:
# Create a length-10 integer array filled with 0s
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [92]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [93]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [94]:
# Create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [95]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [96]:
# Create a 3x3 array of uniformly distributed
# pseudorandom values between 0 and 1
np.random.random((3, 3))

array([[0.3768224 , 0.61680985, 0.58173518],
       [0.68354781, 0.56002971, 0.2681193 ],
       [0.12649303, 0.10642663, 0.04798377]])

In [97]:
# Create a 3x3 array of normally distributed pseudorandom
# values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.51355897,  0.16094441,  1.53248249],
       [ 1.49110265, -0.61486094,  0.10994122],
       [ 0.0404893 , -1.60555543, -1.13645029]])

In [98]:
# Create a 3x3 array of pseudorandom integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[6, 9, 2],
       [3, 2, 8],
       [2, 2, 0]])

In [99]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
# Create an uninitialized array of three integers; the values will be
# whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

### The Basics of NumPy Arrays

In [101]:
rng = np.random.default_rng(seed=1701) # seed for reproducibility
x1 = rng.integers(10, size=6) # one-dimensional array
x2 = rng.integers(10, size=(3, 4)) # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5)) # three-dimensional array

In [102]:
# Attributes
print(f'{x3.ndim = }')
print(f'{x3.shape = }')
print(f'{x3.size = }')
print(f'{x3.dtype = }')

x3.ndim = 3
x3.shape = (3, 4, 5)
x3.size = 60
x3.dtype = dtype('int64')


In [103]:
x1

array([9, 4, 0, 3, 8, 6])

In [104]:
x1[0]

9

In [105]:
x1[len(x1) - 1]

6

In [106]:
x1[-1]

6

In [107]:
x1[-2]

8

In [108]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [109]:
x2[0, 0]

3

In [110]:
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [111]:
x1[0] = 3.14159 # this will be truncated!
x1

array([3, 4, 0, 3, 8, 6])

In [112]:
x1[:3] # first three elements

array([3, 4, 0])

In [113]:
x1[3:] # elements after index 3

array([3, 8, 6])

In [114]:
x1[1:-2] # middle subarray

array([4, 0, 3])

In [115]:
x1[::2] # every second element

array([3, 0, 8])

In [116]:
x1[1::2] # every second element, starting at index 1

array([4, 3, 6])

In [117]:
x1[::-1] # all elements, reversed

array([6, 8, 3, 0, 4, 3])

In [118]:
x1[4::-2] # every second element from index 4, reversed

array([8, 0, 3])

In [119]:
x2[:2, :3] # first two rows & three columns

array([[12,  1,  3],
       [ 4,  0,  2]])

In [120]:
x2[:3, ::2] # three rows, every second column

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [121]:
x2[::-1, ::-1] # all rows & columns, reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [122]:
x2[:, 0] # first column of x2

array([12,  4,  0])

In [123]:
x2[0, :] # first row of x2
# Equivalent to: x2[0]

array([12,  1,  3,  7])

In [126]:
x2_sub = x2[:2, :2]  # By reference
print(x2_sub, end='\n\n', flush=True)

x2_sub[0, 0] = 99
print(x2)

[[99  1]
 [ 4  0]]

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [127]:
x2_sub_copy = x2[:2, :2].copy()  # By value
print(x2_sub_copy, end='\n\n', flush=True)

x2_sub_copy[0, 0] = 42
print(x2)

[[99  1]
 [ 4  0]]

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [129]:
# Reshape
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [130]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) # row vector via reshape

array([[1, 2, 3]])

In [131]:
x.reshape((3, 1)) # column vector via reshape

array([[1],
       [2],
       [3]])

In [132]:
x[np.newaxis, :] # row vector via `newaxis`

array([[1, 2, 3]])

In [133]:
x[:, np.newaxis] # column vector via `newaxis`

array([[1],
       [2],
       [3]])

In [135]:
# Concatenation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [137]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [138]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [139]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [140]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [141]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [150]:
# Splitting
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # split at the 3rd and 5th split points
print(x1, x2, x3) # n split points lead to n+1 arrays

[1 2 3] [99 99] [3 2 1]


In [151]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [153]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [154]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


`np.dconcat` and `np.dsplit` can be used with axis at higher-dimensional arrays

### Computation of NumPyArrays: Universal Functions