In [4]:
import numpy

numpy.__version__

'1.26.4'

In [5]:
import numpy as np  # alias

### Python Lists vs. Python Arrays vs. Numpy Arrays

In [6]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:

type(L[0])

int

In [8]:

L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [9]:
type(L2[0])

str

In [10]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [11]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Integer array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [13]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [14]:
np.array([1, 2, 3, 4], dtype=np.float32)  # specify type

array([1., 2., 3., 4.], dtype=float32)

In [15]:
# Nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [16]:
# Create a length-10 integer array filled with 0s
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [19]:
# Create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
# Create a 3x3 array of uniformly distributed
# pseudorandom values between 0 and 1
np.random.random((3, 3))

array([[0.13888922, 0.51647264, 0.1466806 ],
       [0.572563  , 0.13065452, 0.17224152],
       [0.65296383, 0.12207429, 0.30951925]])

In [22]:
# Create a 3x3 array of normally distributed pseudorandom
# values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.77371831, -1.3672978 ,  0.6338744 ],
       [-0.76287362,  0.42681742,  0.21357078],
       [-1.32638811, -1.48032431,  0.37595707]])

In [23]:
# Create a 3x3 array of pseudorandom integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 9, 5],
       [9, 2, 4],
       [9, 5, 1]])

In [24]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Create an uninitialized array of three integers; the values will be
# whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

### The Basics of NumPy Arrays

In [26]:
rng = np.random.default_rng(seed=1701) # seed for reproducibility
x1 = rng.integers(10, size=6) # one-dimensional array
x2 = rng.integers(10, size=(3, 4)) # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5)) # three-dimensional array

In [27]:
# Attributes
print(f'{x3.ndim = }')
print(f'{x3.shape = }')
print(f'{x3.size = }')
print(f'{x3.dtype = }')

x3.ndim = 3
x3.shape = (3, 4, 5)
x3.size = 60
x3.dtype = dtype('int64')


In [28]:
x1

array([9, 4, 0, 3, 8, 6])

In [29]:
x1[0]

9

In [30]:
x1[len(x1) - 1]

6

In [31]:
x1[-1]

6

In [32]:
x1[-2]

8

In [33]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [34]:
x2[0, 0]

3

In [35]:
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [36]:
x1[0] = 3.14159 # this will be truncated!
x1

array([3, 4, 0, 3, 8, 6])

In [37]:
x1[:3] # first three elements

array([3, 4, 0])

In [38]:
x1[3:] # elements after index 3

array([3, 8, 6])

In [39]:
x1[1:-2] # middle subarray

array([4, 0, 3])

In [40]:
x1[::2] # every second element

array([3, 0, 8])

In [41]:
x1[1::2] # every second element, starting at index 1

array([4, 3, 6])

In [42]:
x1[::-1] # all elements, reversed

array([6, 8, 3, 0, 4, 3])

In [43]:
x1[4::-2] # every second element from index 4, reversed

array([8, 0, 3])

In [44]:
x2[:2, :3] # first two rows & three columns

array([[12,  1,  3],
       [ 4,  0,  2]])

In [45]:
x2[:3, ::2] # three rows, every second column

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [46]:
x2[::-1, ::-1] # all rows & columns, reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [47]:
x2[:, 0] # first column of x2

array([12,  4,  0])

In [48]:
x2[0, :] # first row of x2
# Equivalent to: x2[0]

array([12,  1,  3,  7])

In [49]:
x2_sub = x2[:2, :2]  # By reference
print(x2_sub, end='\n\n', flush=True)

x2_sub[0, 0] = 99
print(x2)

[[12  1]
 [ 4  0]]

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [50]:
x2_sub_copy = x2[:2, :2].copy()  # By value
print(x2_sub_copy, end='\n\n', flush=True)

x2_sub_copy[0, 0] = 42
print(x2)

[[99  1]
 [ 4  0]]

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [51]:
# Reshape
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) # row vector via reshape

array([[1, 2, 3]])

In [53]:
x.reshape((3, 1)) # column vector via reshape

array([[1],
       [2],
       [3]])

In [54]:
x[np.newaxis, :] # row vector via `newaxis`

array([[1, 2, 3]])

In [55]:
x[:, np.newaxis] # column vector via `newaxis`

array([[1],
       [2],
       [3]])

In [56]:
# Concatenation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [57]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [58]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [62]:
# Splitting
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # split at the 3rd and 5th split points
print(x1, x2, x3) # n split points lead to n+1 arrays

[1 2 3] [99 99] [3 2 1]


In [63]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [65]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


`np.dconcat` and `np.dsplit` can be used with axis at higher-dimensional arrays

### Computation of NumPyArrays: Universal Functions

In [66]:
rng = np.random.default_rng(seed=1701)


def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output


values = rng.integers(1, 10, size=5)
compute_reciprocals(values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [74]:
# Measuring it
big_array = rng.integers(1, 100, size=1000000)

%timeit compute_reciprocals(big_array)

1.07 s ± 16.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [77]:
print(compute_reciprocals(values))
print(1.0 / values)

%timeit (1.0 / big_array)

[0.11111111 0.25       1.         0.33333333 0.125     ]
[0.11111111 0.25       1.         0.33333333 0.125     ]
806 μs ± 40.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [78]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [79]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [93]:
# Unary ufuncs

# Array Arithmetics
x = np.arange(4)
print('%10s = %s' % ('x', x))
print('%10s = %s' % ('x + 5', x + 5))
print('%10s = %s' % ('x - 5', x - 5))
print('%10s = %s' % ('-x', -x))
print('%10s = %s' % ('x ** 2', x ** 2))
print('%10s = %s' % ('x % 2', x % 2))

         x = [0 1 2 3]
     x + 5 = [5 6 7 8]
     x - 5 = [-5 -4 -3 -2]
        -x = [ 0 -1 -2 -3]
    x ** 2 = [0 1 4 9]
     x % 2 = [0 1 0 1]


In [94]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [95]:
np.add(x, 2) # Same as x + 2 (wrapper)

array([2, 3, 4, 5])

In [96]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [98]:
np.absolute(x)  # np.abs(x)

array([2, 1, 0, 1, 2])

In [99]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])  # complex
np.abs(x)  # returns the magnitude

array([5., 5., 2., 1.])

In [105]:
# Trigonometric
theta = np.linspace(0, np.pi, 3)
print('%6s = %s' % ('θ', theta))
print('%6s = %s' % ('sin(θ)', np.sin(theta)))
print('%6s = %s' % ('cos(θ)', np.cos(theta)))
print('%6s = %s' % ('tan(θ)', np.tan(theta)))

     θ = [0.         1.57079633 3.14159265]
sin(θ) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(θ) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(θ) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [107]:
# Inverse Trigonometric
x = [-1, 0, 1]
print('%10s = %s' % ('x', x))
print('%10s = %s' % ('arcsin(x)', np.arcsin(x)))
print('%10s = %s' % ('arccos(x)', np.arccos(x)))
print('%10s = %s' % ('arctan(x)', np.arctan(x)))

         x = [-1, 0, 1]
 arcsin(x) = [-1.57079633  0.          1.57079633]
 arccos(x) = [3.14159265 1.57079633 0.        ]
 arctan(x) = [-0.78539816  0.          0.78539816]


In [122]:
# Exponents / Logarithms
x = [1, 2, 3, 4, 10]
print('%10s = %s' % ('x', x))
print('%10s = %s' % ('e^x', np.exp(x)))
print('%10s = %s' % ('2^x', np.exp2(x)))
print('%10s = %s' % ('3^x', np.power(3., x)))
print('%10s = %s' % ('ln(x)', np.log(x)))
print('%10s = %s' % ('log2(x)', np.log2(x)))
print('%10s = %s' % ('log10(x)', np.log10(x)))
# Maintaining Precision
print('%10s = %s' % ('exp(x) - 1', np.expm1(x)))
print('%10s = %s' % ('log(1 + x)', np.log1p(x)))

         x = [1, 2, 3, 4, 10]
       e^x = [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 2.20264658e+04]
       2^x = [   2.    4.    8.   16. 1024.]
       3^x = [3.0000e+00 9.0000e+00 2.7000e+01 8.1000e+01 5.9049e+04]
     ln(x) = [0.         0.69314718 1.09861229 1.38629436 2.30258509]
   log2(x) = [0.         1.         1.5849625  2.         3.32192809]
  log10(x) = [0.         0.30103    0.47712125 0.60205999 1.        ]
exp(x) - 1 = [1.71828183e+00 6.38905610e+00 1.90855369e+01 5.35981500e+01
 2.20254658e+04]
log(1 + x) = [0.69314718 1.09861229 1.38629436 1.60943791 2.39789527]


In [130]:
from scipy import special  # More ufuncs

# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print('%12s = %s' % ('x', x))
print('%12s = %s' % ('gamma(x)', special.gamma(x)))
print('%12s = %s' % ('ln|gamma(x)|', special.gammaln(x)))
print('%12s = %s' % ('beta(x, 2)', special.beta(x, 2)))
print()

# Error function (integral of Gaussian),
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print('%10s = %s' % ('x', x))
print('%10s = %s' % ('erf(x)', special.erf(x)))
print('%10s = %s' % ('erfc(x)', special.erfc(x)))
print('%10s = %s' % ('erfinv(x)', special.erfinv(x)))

           x = [1, 5, 10]
    gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
  beta(x, 2) = [0.5        0.03333333 0.00909091]

         x = [0.  0.3 0.7 1. ]
    erf(x) = [0.         0.32862676 0.67780119 0.84270079]
   erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
 erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [134]:
# Specifying output
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

# using views
y = np.zeros(10)
np.power(2, x, out=y[::2]) # Note that: y[::2] = 2 ** x generates copies
print(y)

[ 0. 10. 20. 30. 40.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [135]:
# Aggregations
x = np.arange(1, 6)
np.add.reduce(x)  # summation

15

In [136]:
np.multiply.reduce(x)  # production

120

In [137]:
# Accumulates the results of a reduction
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [139]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [140]:
# Outer Products
x = np.arange(1, 6)
np.multiply.outer(x, x)  # calculates [f(a, b) = a * b]: a × b → f(a, b) ∀a,b∈x

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

### Aggregations:

In [143]:
rng = np.random.default_rng()
L = rng.random(100)
print(sum(L))
print(np.sum(L))  # Note that function arguments are not the same

54.48988066273366
54.48988066273364


In [144]:

big_array = rng.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

56 ms ± 189 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
176 μs ± 5.86 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [147]:
print(min(big_array), max(big_array))
print(np.min(big_array), np.max(big_array))
%timeit min(big_array)
%timeit np.min(big_array)

2.946437968054383e-07 0.9999991180883955
2.946437968054383e-07 0.9999991180883955
42.2 ms ± 481 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
108 μs ± 2.2 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [148]:
print(big_array.min(), big_array.max(), big_array.sum())  # alt syntax for np aggregates

2.946437968054383e-07 0.9999991180883955 499536.4394650321


In [150]:
M = rng.integers(0, 10, (3, 4))
print(M)
M.sum()

[[9 1 8 3]
 [1 9 3 8]
 [8 5 0 5]]


60

In [155]:
print(M.min(axis=0))  # min of each column
print(M.max(axis=1))  # max of each row
# axis is the dimension to collapse / reduce

[1 1 0 3]
[9 9 8]
